const fs=require('node:fs/promises');
const fsSync=require('node:fs');
const path=require('node:path');
const os=require('node:os');
const {execFile}=require('node:child_process');
const {promisify}=require('node:util');
const {DatabaseSync}=require('node:sqlite');
const {extract,rowRecords}=require('./documents.cjs');
const {safeUrl,hash,clean}=require('./store.cjs');
const run=promisify(execFile);
const extensions=new Set(['.txt','.md','.csv','.ics','.doc','.docx','.xls','.xlsx','.pdf','.jpg','.jpeg','.png','.heic','.gif','.webp','.mov','.mp4','.m4v','.mp3','.m4a','.wav','.aac','.ogg']);
const media=new Set(['.jpg','.jpeg','.png','.heic','.gif','.webp','.mov','.mp4','.m4v','.mp3','.m4a','.wav','.aac','.ogg']);
const skipDirs=new Set(['node_modules','.git','.svn','.cache','Caches','Cache','Pods','vendor','dist','build','.next','.venv','venv','release','Library']);
const sensitive=/(?:^|[ _.-])(passwords?|credentials?|secrets?|tokens?|id_rsa|id_ed25519|\.env)(?:$|[ _.-])|密码|验证码|身份证|护照|私钥|密钥/i;
async function exists(file){try{await fs.access(file);return true;}catch{return false;}}
async function dirs(root){try{return (await fs.readdir(root,{withFileTypes:true})).filter(item=>item.isDirectory()).map(item=>path.join(root,item.name));}catch{return [];}}
function readDb(file,fn){const read=target=>{const db=new DatabaseSync(target,{readOnly:true});try{db.exec('PRAGMA query_only=ON; PRAGMA busy_timeout=1000; BEGIN');return fn(db);}finally{db.close();}};try{return read(file);}catch(error){if(!/locked|busy/i.test(error.message))throw error;}
  const temp=fsSync.mkdtempSync(path.join(os.tmpdir(),'life-archive-snapshot-'));fsSync.chmodSync(temp,0o700);const target=path.join(temp,'snapshot.sqlite');
  const signature=source=>{try{const stat=fsSync.statSync(source,{bigint:true});return `${stat.size}:${stat.mtimeNs}`;}catch(error){if(error.code==='ENOENT')return '';throw error;}};
  try{for(let attempt=0;attempt<3;attempt++){const before=[signature(file),signature(file+'-wal')];fsSync.copyFileSync(file,target);fsSync.chmodSync(target,0o600);if(before[1]){fsSync.copyFileSync(file+'-wal',target+'-wal');fsSync.chmodSync(target+'-wal',0o600);}else fsSync.rmSync(target+'-wal',{force:true});const after=[signature(file),signature(file+'-wal')];if(before.join('|')===after.join('|'))return read(target);}throw new Error('数据库持续变化，未取得稳定只读副本，请稍后重试');}finally{fsSync.rmSync(temp,{recursive:true,force:true});}}
function table(db,name){return !!db.prepare('SELECT name FROM sqlite_master WHERE type IN (\'table\',\'view\') AND name=?').get(name);}
function columns(db,name){return db.prepare(`PRAGMA table_info("${name.replace(/"/g,'""')}")`).all().map(item=>item.name);}
function appleDate(value){const n=typeof value==='bigint'?value:Number(value);const ms=typeof n==='bigint'?Number(n>1000000000000n?n/1000000n:n*1000n):(n>1e12?n/1e6:n*1000);return new Date(ms+978307200000).toISOString();}
function chromeDate(value){return new Date(Number(BigInt(value)/1000n-11644473600000n)).toISOString();}
function allLarge(db,sql){const statement=db.prepare(sql);statement.setReadBigInts(true);return statement.all();}
function errorStatus(error){return /EACCES|EPERM|operation not permitted|authorization denied|unable to open database/i.test(error.message)?'blocked':'error';}
class Collector{
  constructor(store,{home=os.homedir(),onProgress=()=>{}}={}){this.store=store;this.home=home;this.onProgress=onProgress;this.running=false;this.cancelled=false;this.stats={};}
  enabled(id){return !this.store.setting('disabledSources',[]).includes(id);}
  async source(id,name,fn){if(!this.enabled(id)){this.store.source(id,{name,status:'paused',detail:'已暂停此来源',checkedAt:new Date().toISOString()});return;}
    this.onProgress({source:name});this.store.source(id,{name,status:'scanning',detail:'正在检查可读数据'});try{const result=await fn();this.store.source(id,{name,status:result?.status??'ready',detail:result?.detail??'读取完成',checkedAt:new Date().toISOString(),...result});}catch(error){this.store.source(id,{name,status:errorStatus(error),detail:errorStatus(error)==='blocked'?'系统或应用限制访问；未绕过保护。可在系统隐私设置中为本工具授权后重试。':'此来源读取失败，其他来源继续。'+clean(error.message,140),checkedAt:new Date().toISOString()});}}
  add(source,record){if(this.store.add({source,...record}))this.stats.added++;}
  async scan(){if(this.running)return {busy:true};this.running=true;this.cancelled=false;this.stats={added:0,files:0,skipped:0,startedAt:new Date().toISOString()};try{
    await this.source('apps','电脑上的应用',()=>this.apps());
    await this.source('activity','应用使用时间',async()=>({status:this.store.setting('tracking',true)?'ready':'paused',detail:'运行期间每 15 秒记录前台应用；空闲、锁屏或退出工具时停止。不读取屏幕内容。'}));
    await this.source('files','电脑文件与导出记录',()=>this.files());
    for(const [id,name,root] of [['chrome','Chrome',path.join(this.home,'Library/Application Support/Google/Chrome')],['edge','Edge',path.join(this.home,'Library/Application Support/Microsoft Edge')],['brave','Brave',path.join(this.home,'Library/Application Support/BraveSoftware/Brave-Browser')],['arc','Arc',path.join(this.home,'Library/Application Support/Arc/User Data')]]){if(this.cancelled)break;await this.source(id,name+' 浏览记录',()=>this.chromium(id,root));}
    if(!this.cancelled)await this.source('firefox','Firefox 浏览记录',()=>this.firefox());
    if(!this.cancelled)await this.source('safari','Safari 浏览记录',()=>this.safari(path.join(this.home,'Library/Safari/History.db'),'safari'));
    if(!this.cancelled)await this.source('messages','Apple 信息',()=>this.messages(path.join(this.home,'Library/Messages/chat.db'),'messages'));
    if(!this.cancelled)await this.source('calendar','Apple 日历',()=>this.calendar());
    if(!this.cancelled)await this.source('photos','照片图库',()=>this.photos());
    if(!this.cancelled)await this.source('wechat','微信本地数据',()=>this.wechat());
    if(!this.cancelled)await this.source('iphone','iPhone 本地备份',()=>this.iphone());
    if(!this.cancelled)await this.source('android','Android 连接',()=>this.android());
    this.stats.finishedAt=new Date().toISOString();this.store.setSetting('lastScan',this.stats.finishedAt);this.store.setSetting('scanStats',this.stats);return this.stats;
  }finally{this.running=false;this.onProgress({done:true,stats:this.stats});}}
  async apps(){const found=[];const walk=async(root,depth=0)=>{for(const item of await dirs(root)){if(item.endsWith('.app'))found.push({name:path.basename(item,'.app'),path:item,access:'可记录使用时间；内容取决于各来源授权或文件导出'});else if(depth<2)await walk(item,depth+1);}};for(const root of ['/Applications','/System/Applications',path.join(this.home,'Applications')])await walk(root);this.store.setSetting('installedApps',found.sort((a,b)=>a.name.localeCompare(b.name)));return {detail:`检测到 ${found.length} 个应用。应用清单不等于已读取其聊天或订单内容；所有应用均可通过前台使用记录关联。`};}
  async files(){let roots=this.store.setting('folders',null);if(!roots){roots=['Desktop','Documents','Downloads','Pictures','Movies','Music'].map(name=>path.join(this.home,name));this.store.setSetting('folders',roots);}let readable=0,denied=0;const excluded=[this.store.directory,...this.store.setting('excludedFolders',[])].map(folder=>path.resolve(folder));const visited=new Set();
    const walk=async(root,depth=0)=>{if(this.cancelled||this.stats.files>=15000||depth>12)return;if(excluded.some(folder=>root===folder||root.startsWith(folder+path.sep)))return;if(visited.has(root))return;visited.add(root);let entries;try{entries=await fs.readdir(root,{withFileTypes:true});readable++;}catch(error){if(['EACCES','EPERM'].includes(error.code))denied++;return;}
      for(const item of entries){if(this.cancelled||this.stats.files>=15000)break;if(item.name.startsWith('.')||sensitive.test(item.name))continue;const file=path.join(root,item.name);if(item.isDirectory()){if(!skipDirs.has(item.name)&&!item.name.endsWith('.app')&&!item.name.endsWith('.photoslibrary'))await walk(file,depth+1);continue;}if(!item.isFile()||!extensions.has(path.extname(file).toLowerCase()))continue;this.stats.files++;try{const stat=await fs.stat(file);const signature=hash([file,stat.size,stat.mtimeMs].join('|'));if(this.store.setting('file:'+hash(file),'')===signature)continue;let content={text:'',detail:'照片、视频或录音原件索引；本版不自动识别画面或转写声音'};const isMedia=media.has(path.extname(file).toLowerCase());if(!isMedia){try{content=await extract(file);}catch(error){content={text:'',detail:'原件可读，内容解析未完成：'+clean(error.message,120)};}}
        const relative=path.relative(this.home,file);this.add('files',{key:'file:'+file,kind:isMedia?'media':'file',title:path.basename(file),body:content.text||content.detail,occurredAt:stat.mtime,path:file,meta:{size:stat.size,modifiedAt:stat.mtime.toISOString(),evidence:'文件修改时间，不代表完成事件或拍摄时间',detail:content.detail??'已读取文字',relative}});for(const record of rowRecords(content.rows,file))this.add('files',{...record,path:file});this.store.setSetting('file:'+hash(file),signature);
      }catch{this.stats.skipped++;}if(this.stats.files%20===0)await new Promise(resolve=>setTimeout(resolve,0));}
    };for(const root of roots)await walk(path.resolve(root));return {status:denied?'partial':readable?'ready':'missing',detail:`检查 ${this.stats.files} 个文件；${denied} 个目录不可访问。自动跳过隐藏目录、凭据文件、程序依赖和自身档案。图片/影音索引原件；Word、Excel、PDF 提取可读文字。${this.stats.files>=15000?'本次达到 15,000 个文件限制，请分批选择目录。':''}`};}
  async chromium(id,root){const profiles=await dirs(root);let databases=0,failures=0;for(const profile of profiles){const file=path.join(profile,'History');if(!await exists(file))continue;try{readDb(file,db=>{if(!table(db,'visits')||!table(db,'urls'))throw new Error('不支持此浏览器数据库结构');for(const row of allLarge(db,'SELECT v.id,v.visit_time,u.url,u.title FROM visits v JOIN urls u ON u.id=v.url ORDER BY v.visit_time DESC LIMIT 20000')){const url=safeUrl(row.url);if(!url)continue;this.add(id,{key:`${id}:${profile}:${row.id}`,kind:'browser',title:row.title||new URL(url).hostname,body:'浏览记录表明访问过这个页面；不代表已购买、完成或认可其中内容。',occurredAt:chromeDate(row.visit_time),url,meta:{profile:path.basename(profile)}});}});databases++;}catch{failures++;}}
    return {status:failures?'partial':databases?'ready':'missing',detail:databases?`已读取 ${databases} 个浏览器资料库；网址查询参数和片段已去除。${failures?failures+' 个资料库无法读取。':''}`:failures?'发现浏览器资料库但无法读取。':'未发现可用浏览记录'};}
  async firefox(){const profiles=await dirs(path.join(this.home,'Library/Application Support/Firefox/Profiles'));let found=0;for(const profile of profiles){const file=path.join(profile,'places.sqlite');if(!await exists(file))continue;readDb(file,db=>{for(const row of allLarge(db,'SELECT v.id,v.visit_date,p.title,p.url FROM moz_historyvisits v JOIN moz_places p ON p.id=v.place_id ORDER BY v.visit_date DESC LIMIT 20000')){if(!safeUrl(row.url))continue;this.add('firefox',{key:'firefox:'+profile+':'+row.id,kind:'browser',title:row.title||new URL(row.url).hostname,url:row.url,body:'来自 Firefox 访问记录',occurredAt:new Date(Number(row.visit_date/1000n)).toISOString()});}});found++;}return {status:found?'ready':'missing',detail:found?`已读取 ${found} 个 Firefox 资料库`:'未发现可读 Firefox 浏览记录'};}
  async safari(file,source){if(!await exists(file))return {status:'missing',detail:'未发现可访问的 Safari 历史数据库；可能未使用或受隐私权限限制'};readDb(file,db=>{for(const row of db.prepare('SELECT v.id,v.visit_time,v.title,i.url FROM history_visits v JOIN history_items i ON i.id=v.history_item ORDER BY v.visit_time DESC LIMIT 20000').all()){if(!safeUrl(row.url))continue;this.add(source,{key:`${source}:${file}:${row.id}`,kind:'browser',title:row.title||new URL(row.url).hostname,body:'来自 Safari 访问记录',occurredAt:appleDate(row.visit_time),url:row.url});}});return {detail:'已读取 Safari 可访问的浏览记录'};}
  async messages(file,source){if(!await exists(file))return {status:'missing',detail:'未发现可访问的短信/iMessage 数据；可能受系统权限限制'};readDb(file,db=>{const fields=columns(db,'message');if(!fields.includes('text'))throw new Error('数据库结构不受支持');for(const row of allLarge(db,'SELECT m.ROWID id,m.text,m.date,m.is_from_me,h.id contact FROM message m LEFT JOIN handle h ON h.ROWID=m.handle_id WHERE m.text IS NOT NULL AND length(m.text)>0 ORDER BY m.date DESC LIMIT 20000')){this.add(source,{key:`${source}:${file}:${row.id}`,kind:'message',title:row.is_from_me?'发出的信息':'收到的信息',body:row.text,occurredAt:appleDate(row.date),meta:{direction:row.is_from_me?'outgoing':'incoming',contact:clean(row.contact,200),evidence:'只记录数据库中可访问的文字消息，不代表完整聊天'}});}});return {detail:'已读取可访问的文字消息；图片、语音和富文本消息不保证完整'};}
  async calendar(){for(const file of [path.join(this.home,'Library/Calendars/Calendar.sqlitedb'),path.join(this.home,'Library/Group Containers/group.com.apple.calendar/Calendar.sqlitedb')]){if(!await exists(file))continue;readDb(file,db=>{if(!table(db,'CalendarItem'))throw new Error('当前日历数据库结构暂未适配');const fields=columns(db,'CalendarItem');if(!fields.includes('summary')||!fields.includes('start_date'))throw new Error('当前日历字段暂未适配');for(const row of db.prepare('SELECT ROWID id,summary,start_date FROM CalendarItem WHERE summary IS NOT NULL ORDER BY start_date DESC LIMIT 10000').all())this.add('calendar',{key:`calendar:${file}:${row.id}`,kind:'calendar',title:row.summary,body:'日历中的计划；未确认实际发生。',occurredAt:appleDate(row.start_date)});});return {detail:'已读取可访问的日程标题与计划时间'};}return {status:'missing',detail:'未发现可读日历数据库；可将 .ics 导出到已选文件夹'};}
  async photos(){const libraries=(await dirs(path.join(this.home,'Pictures'))).filter(dir=>dir.endsWith('.photoslibrary'));let found=0;for(const library of libraries){const file=path.join(library,'database/Photos.sqlite');if(!await exists(file))continue;readDb(file,db=>{if(!table(db,'ZASSET'))throw new Error('当前照片图库结构暂未适配');const fields=columns(db,'ZASSET');if(!fields.includes('ZFILENAME')||!fields.includes('ZDATECREATED'))throw new Error('当前照片字段暂未适配');for(const row of db.prepare('SELECT Z_PK id,ZFILENAME name,ZDATECREATED created FROM ZASSET WHERE ZFILENAME IS NOT NULL ORDER BY ZDATECREATED DESC LIMIT 20000').all())this.add('photos',{key:`photo:${library}:${row.id}`,kind:'media',title:row.name,body:'照片图库中的原件索引；未读取画面内容，iCloud 原件可能未下载。',occurredAt:appleDate(row.created)});});found++;}return {status:found?'ready':'missing',detail:found?`已读取 ${found} 个本地照片图库的名称与日期`:'未发现可访问的照片图库。相机照片或影音放到文件夹即可归档索引。'};}
  async wechat(){const roots=[path.join(this.home,'Library/Containers/com.tencent.xinWeChat'),path.join(this.home,'Library/Containers/com.tencent.WeChat'),path.join(this.home,'Library/Group Containers/5A4RE8SF68.com.tencent.xinWeChat')];let present=false,readable=false,databases=0,encrypted=0;const inspect=async(root,depth=0)=>{let list;try{list=await fs.readdir(root,{withFileTypes:true});present=true;readable=true;}catch(error){if(['EPERM','EACCES'].includes(error.code))present=true;return;}for(const entry of list){if(entry.isSymbolicLink())continue;const file=path.join(root,entry.name);if(entry.isDirectory()&&depth<9&&!['Cache','Caches','temp'].includes(entry.name))await inspect(file,depth+1);else if(entry.isFile()&&/\.(db|sqlite)$/i.test(entry.name)&&databases<200){databases++;const handle=await fs.open(file,'r');try{const bytes=Buffer.alloc(16);await handle.read(bytes,0,16,0);if(!bytes.toString().startsWith('SQLite format 3'))encrypted++;}finally{await handle.close();}}}};for(const root of roots)await inspect(root);return {status:encrypted?'blocked':present&&!readable?'blocked':present?'unsupported':'missing',detail:encrypted?`发现 ${databases} 个数据库，其中 ${encrypted} 个使用非明文格式，未解密或提取密钥。可读取其文件导出的聊天文字、图片、录音。`:present&&!readable?'微信目录受系统访问限制。':present?'检测到微信本地目录；当前版本未适配此聊天库结构。可把聊天或文件保存到采集文件夹。':'未发现微信本地数据；不代表手机没有微信。'};}
  async iphone(){const root=path.join(this.home,'Library/Application Support/MobileSync/Backup');const backups=await dirs(root);if(!backups.length)return {status:'missing',detail:'未发现本机可访问的 iPhone Finder 备份。连接手机并信任电脑后，可在 Finder 创建本地备份；本版读取未加密备份，不实时读取手机所有应用。'};let read=0,encrypted=0;for(const backup of backups){const manifest=path.join(backup,'Manifest.db');if(!await exists(manifest))continue;try{const plist=await run('/usr/bin/plutil',['-convert','json','-o','-',path.join(backup,'Manifest.plist')],{maxBuffer:2e6});if(JSON.parse(plist.stdout).IsEncrypted){encrypted++;continue;}}catch{}
    const signature=await fs.open(manifest,'r');const header=Buffer.alloc(16);try{await signature.read(header,0,16,0);}finally{await signature.close();}if(!header.toString().startsWith('SQLite format 3')){encrypted++;continue;}const records=readDb(manifest,db=>db.prepare("SELECT fileID,domain,relativePath FROM Files WHERE flags=1 AND (relativePath LIKE '%History.db' OR relativePath LIKE '%sms.db' OR relativePath LIKE 'Media/DCIM/%') LIMIT 30000").all());for(const row of records){const file=path.join(backup,row.fileID.slice(0,2),row.fileID);if(!await exists(file))continue;const source='iphone';try{if(row.relativePath.endsWith('/sms.db'))await this.messages(file,source);else if(row.relativePath.endsWith('/History.db'))await this.safari(file,source);else if(row.relativePath.startsWith('Media/DCIM/')){const stat=await fs.stat(file);this.add(source,{key:'iphone:'+backup+':'+row.fileID,kind:'media',title:path.basename(row.relativePath),body:'来自 iPhone 本地备份的相机文件；日期为备份文件时间，不代表拍摄时间。',occurredAt:stat.mtime,path:file,meta:{originalName:path.basename(row.relativePath)}});}}catch{this.stats.skipped++;}}read++;}
    return {status:encrypted?'partial':read?'ready':'missing',detail:`已读取 ${read} 份未加密备份中的可访问短信、Safari 和相机索引；${encrypted} 份加密备份跳过。备份以创建时的内容为准，其他应用内容未适配。`};}
  async android(){const candidates=[this.store.setting('adbPath',''),path.join(this.home,'Library/Android/sdk/platform-tools/adb'),'/opt/homebrew/bin/adb','/usr/local/bin/adb'].filter(Boolean);let adb='';for(const file of candidates)if(await exists(file)){adb=file;break;}if(!adb)return {status:'missing',detail:'本机未发现 Android 官方 adb 工具。手机连接、开启 USB 调试并授权后可接入；无需 root。本版不会代你接受 Android SDK 许可。'};const {stdout}=await run(adb,['devices'],{timeout:12000,maxBuffer:2e6});const rows=stdout.split('\n').slice(1).map(line=>line.trim().split(/\s+/)).filter(row=>row[0]);const devices=rows.filter(row=>row[1]==='device');if(!devices.length)return {status:rows.length?'blocked':'missing',detail:rows.length?'手机尚未授权 USB 调试或连接离线；请在手机确认后重试。':'未检测到已授权 Android 手机。'};let apps=0;for(const [serial] of devices){const result=await run(adb,['-s',serial,'shell','pm','list','packages'],{timeout:15000,maxBuffer:4e6});const packages=result.stdout.split('\n').map(line=>line.replace(/^package:/,'').trim()).filter(Boolean);apps+=packages.length;this.store.setSetting('androidApps:'+hash(serial),packages);}
    return {status:'partial',detail:`检测到 ${devices.length} 台已授权手机和 ${apps} 个应用包。已接入应用清单；手机聊天、订单与使用历史需各应用导出或专用权限，本版尚未自动读取。`};}
}
module.exports={Collector,exists,readDb,appleDate,chromeDate,errorStatus,sensitive,extensions};
