const fs=require('node:fs/promises');
const path=require('node:path');
const {unzipSync,strFromU8}=require('fflate');
const {clean}=require('./store.cjs');
const MAX_BYTES=12*1024*1024;
const entities=value=>value.replace(/&#x([\da-f]+);/gi,(_,x)=>String.fromCodePoint(parseInt(x,16))).replace(/&#(\d+);/g,(_,x)=>String.fromCodePoint(Number(x))).replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,'&');
const xmlText=value=>entities(value.replace(/<\/(?:w:p|w:tr)>/g,'\n').replace(/<[^>]*>/g,' ')).replace(/[ \t]+/g,' ').replace(/ *\n */g,'\n').trim();
function csv(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw new Error('CSV 格式不完整');row.push(cell);if(row.some(v=>v.trim()))rows.push(row);return rows;}
function unzip(buffer){let expanded=0;return unzipSync(buffer,{filter:file=>{if(!/^(word\/document\.xml|xl\/sharedStrings\.xml|xl\/worksheets\/sheet\d+\.xml)$/.test(file.name))return false;if(file.originalSize>8*1024*1024)throw new Error('文档解压大小超出限制');expanded+=file.originalSize;if(expanded>20*1024*1024)throw new Error('文档解压大小超出限制');return true;}});}
function sheetRows(xml,strings){return [...xml.matchAll(/<row(?:\s[^>]*)?>([\s\S]*?)<\/row>/g)].slice(0,2000).map(row=>{const values=[];for(const cell of row[1].matchAll(/<c(\s[^>]*?)>([\s\S]*?)<\/c>/g)){const reference=cell[1].match(/\br="([A-Z]+)\d+"/)?.[1];let index=values.length;if(reference){index=0;for(const letter of reference)index=index*26+letter.charCodeAt(0)-64;index--;}if(index>1000)continue;while(values.length<=index)values.push('');const value=cell[2].match(/<v>([\s\S]*?)<\/v>/)?.[1]??'';values[index]=/\bt="s"/.test(cell[1])?strings[Number(value)]??'':/\bt="inlineStr"/.test(cell[1])?xmlText(cell[2]):entities(value);}return values;});}
async function extract(file){const stat=await fs.stat(file);if(stat.size>MAX_BYTES)return {text:'',detail:'原件可访问；文件较大，本次仅归档名称与时间'};const ext=path.extname(file).toLowerCase();const buffer=await fs.readFile(file);if(['.txt','.md','.csv','.ics','.html','.htm','.json'].includes(ext)){const text=buffer.toString('utf8').replace(/^\uFEFF/,'');return {text:clean(ext.startsWith('.ht')?xmlText(text):text),rows:ext==='.csv'?csv(text).slice(0,5000):undefined};}
  if(ext==='.docx'){const files=unzip(buffer);return {text:clean(xmlText(strFromU8(files['word/document.xml']??new Uint8Array())))};}
  if(ext==='.xlsx'){const files=unzip(buffer);const shared=strFromU8(files['xl/sharedStrings.xml']??new Uint8Array());const strings=[...shared.matchAll(/<si(?:\s[^>]*)?>([\s\S]*?)<\/si>/g)].map(match=>xmlText(match[1]));const sheets=[];let firstRows=[];for(const key of Object.keys(files).filter(key=>key.startsWith('xl/worksheets/')).sort().slice(0,10)){const rows=sheetRows(strFromU8(files[key]),strings);if(!firstRows.length)firstRows=rows;sheets.push(rows.map(row=>row.join(' | ')).join('\n'));}return {text:clean(sheets.join('\n\n')),rows:firstRows};}
  if(ext==='.pdf'){const {PDFParse}=require('pdf-parse');const parser=new PDFParse({data:new Uint8Array(buffer)});try{const result=await parser.getText({first:30});return {text:clean(result.text),detail:result.text.trim()?'已提取可读取的文字':'未发现文字层，可保存原件；扫描件尚未进行 OCR'};}finally{await parser.destroy();}}
  return {text:'',detail:['.doc','.xls'].includes(ext)?'已保留原件索引；旧版 Office 格式本版暂未解析':'原件索引'};
}
function rowRecords(rows,filename){if(!rows?.length)return [];const headers=rows[0].map(value=>String(value).trim());const find=pattern=>headers.findIndex(header=>pattern.test(header));const titleIndex=find(/^(标题|事件|商品名称|商品|菜品|商品信息|订单内容|title|product|item|food)$/i);const dayIndex=find(/^(日期|时间|下单时间|支付时间|订单时间|date|time|created_at)$/i);if(titleIndex<0||dayIndex<0)return [];return rows.slice(1).map((values,index)=>{const raw=String(values[dayIndex]??''),match=raw.match(/(\d{4})[-/年](\d{1,2})[-/月](\d{1,2})(?:日)?(?:[ T](\d{1,2}):?(\d{2})?(?::\d{2})?)?/);if(!match)return null;const date=`${match[1]}-${match[2].padStart(2,'0')}-${match[3].padStart(2,'0')}T${(match[4]??'12').padStart(2,'0')}:${match[5]??'00'}:00+08:00`;return {key:`row:${filename}:${index}:${JSON.stringify(values)}`,title:String(values[titleIndex]??''),body:headers.map((name,i)=>`${name}：${values[i]??''}`).join('\n'),occurredAt:date,kind:/订单|商品|菜品/.test(headers.join(' '))?'order':'file',meta:{evidence:'来自文件中的日期与字段；订单不等于实际食用或使用'}};}).filter(row=>row&&row.title&&Number.isFinite(new Date(row.occurredAt).getTime()));}
module.exports={extract,csv,rowRecords,xmlText};
