const fs=require('node:fs');
const path=require('node:path');
const crypto=require('node:crypto');
const {DatabaseSync}=require('node:sqlite');
const hash=value=>crypto.createHash('sha256').update(String(value)).digest('hex');
function clean(value,max=20000){return String(value??'').replace(/\b(?:sk-|ghp_|github_pat_|AKIA)[A-Za-z0-9_-]{12,}\b/g,'[已隐藏凭据]').replace(/((?:验证码|一次性密码|verification code|one.time password)\s*[:：]?\s*)\d{4,8}/gi,'$1[已隐藏]').replace(/((?:password|passwd|token|api[_ -]?key|密码|密钥)\s*[:=：]\s*)[^\s，。;；]+/gi,'$1[已隐藏]').slice(0,max);}
function safeUrl(value){try{const url=new URL(value);if(!['http:','https:'].includes(url.protocol))return '';url.username='';url.password='';url.search='';url.hash='';return url.href;}catch{return '';}}
const dateParts=value=>{const date=new Date(value);return {day:new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai'}).format(date),time:new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Shanghai',hour:'2-digit',minute:'2-digit',hour12:false}).format(date)};};
class Store{
  constructor(directory){fs.mkdirSync(directory,{recursive:true,mode:0o700});this.directory=directory;this.path=path.join(directory,'archive.sqlite');this.db=new DatabaseSync(this.path);this.db.exec('PRAGMA journal_mode=WAL; PRAGMA busy_timeout=3000; CREATE TABLE IF NOT EXISTS records(id TEXT PRIMARY KEY, source TEXT NOT NULL, kind TEXT NOT NULL, title TEXT NOT NULL, body TEXT NOT NULL, occurred_at TEXT NOT NULL, path TEXT NOT NULL DEFAULT \'\', url TEXT NOT NULL DEFAULT \'\', meta TEXT NOT NULL DEFAULT \'{}\', created_at TEXT NOT NULL); CREATE INDEX IF NOT EXISTS record_time ON records(occurred_at); CREATE INDEX IF NOT EXISTS record_source ON records(source); CREATE TABLE IF NOT EXISTS sources(id TEXT PRIMARY KEY, payload TEXT NOT NULL); CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY, value TEXT NOT NULL);');fs.chmodSync(this.path,0o600);}
  setting(key,fallback){const row=this.db.prepare('SELECT value FROM settings WHERE key=?').get(key);return row?JSON.parse(row.value):fallback;}
  setSetting(key,value){this.db.prepare('INSERT INTO settings VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(key,JSON.stringify(value));}
  add(record){const time=new Date(record.occurredAt??Date.now());if(Number.isNaN(time.getTime()))return false;const id=hash(record.key??[record.source,record.kind,record.title,time.toISOString(),record.path??record.url??''].join('|'));const before=this.db.prepare('SELECT id FROM records WHERE id=?').get(id);this.db.prepare('INSERT INTO records VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,body=excluded.body,occurred_at=excluded.occurred_at,path=excluded.path,url=excluded.url,meta=excluded.meta').run(id,record.source,record.kind,clean(record.title,200)||'一条生活线索',clean(record.body),time.toISOString(),record.path??'',safeUrl(record.url),JSON.stringify(record.meta??{}),new Date().toISOString());return !before;}
  source(id,update){const previous=this.db.prepare('SELECT payload FROM sources WHERE id=?').get(id);const data={...(previous?JSON.parse(previous.payload):{}),id,...update};this.db.prepare('INSERT INTO sources VALUES(?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload').run(id,JSON.stringify(data));return data;}
  sources(){const counts=Object.fromEntries(this.db.prepare('SELECT source,count(*) n FROM records GROUP BY source').all().map(row=>[row.source,row.n]));return this.db.prepare('SELECT payload FROM sources').all().map(row=>{const item=JSON.parse(row.payload);return {...item,count:counts[item.id]??0};});}
  list({query='',source='',kind='',day='',limit=200,offset=0}={}){const where=[],params=[];if(query){where.push('(title LIKE ? ESCAPE \'\\\' OR body LIKE ? ESCAPE \'\\\')');const term='%'+String(query).replace(/[\\%_]/g,'\\$&')+'%';params.push(term,term);}if(source){where.push('source=?');params.push(source);}if(kind){where.push('kind=?');params.push(kind);}if(day){const start=new Date(day+'T00:00:00+08:00');if(!Number.isNaN(start.getTime())){where.push('occurred_at>=? AND occurred_at<?');params.push(start.toISOString(),new Date(start.getTime()+86400000).toISOString());}}const clause=where.length?' WHERE '+where.join(' AND '):'';const total=this.db.prepare('SELECT count(*) n FROM records'+clause).get(...params).n;const rows=this.db.prepare('SELECT * FROM records'+clause+' ORDER BY occurred_at DESC LIMIT ? OFFSET ?').all(...params,Math.min(500,Math.max(1,Number(limit)||200)),Math.max(0,Number(offset)||0));return {total,records:rows.map(({occurred_at,created_at,...row})=>({...row,occurredAt:occurred_at,createdAt:created_at,meta:JSON.parse(row.meta)}))};}
  summary(){const today=dateParts(Date.now()).day;return {total:this.db.prepare('SELECT count(*) n FROM records').get().n,today:this.list({day:today,limit:1}).total,byKind:this.db.prepare('SELECT kind,count(*) n FROM records GROUP BY kind').all(),appCount:this.setting('installedApps',[]).length,sources:this.sources(),lastScan:this.setting('lastScan',null),scanStats:this.setting('scanStats',null),directory:this.directory};}
  export(){const rows=this.db.prepare('SELECT * FROM records ORDER BY occurred_at').all();return {version:1,exportedAt:new Date().toISOString(),timezone:'Asia/Shanghai',entries:rows.map(row=>{const {day,time}=dateParts(row.occurred_at);return {id:row.id,day,time,title:row.title.slice(0,120),body:row.body+(row.url?'\n'+row.url:''),category:({browser:'学习',activity:'工作',message:'关系',order:'生活',calendar:'生活',file:'生活',media:'生活'})[row.kind]??'生活',mood:null,people:[],tags:[row.kind,row.source],place:'',source:'activity',confirmed:false,sourceKey:'desktop:'+row.id,evidenceIds:[],media:[]};}),decisions:[],note:'自动采集的是来源线索；文件原件仍在设备上，需确认实际经历。'};}
  close(){this.db.close();}
}
module.exports={Store,hash,clean,safeUrl,dateParts};
