const fs = require('node:fs');
const path = require('node:path');
const root = path.join(__dirname, '..', 'site');
const base = 'https://zurenze1.github.io/life-archive/';
const personal = 'https://zurenze1.github.io/zurenze-personal-site/';
const repo = 'https://github.com/zurenze1/life-archive';
const release = `${repo}/releases/tag/v1.0.0`;
const download = `${repo}/releases/download/v1.0.0/LifeArchive-1.0.0-arm64.dmg`;
const date = '2026-10-06';
const styleVersion = require('node:crypto').createHash('sha256').update(fs.readFileSync(path.join(root, 'assets/style.css'))).digest('hex').slice(0,12);
const person = {'@type':'Person','@id':`${personal}#person`,name:'祖仁泽',url:`${base}author/`,sameAs:[personal,'https://github.com/zurenze1']};
const app = {'@type':'WebApplication','@id':`${base}#application`,name:'人生档案',alternateName:'Life Archive',url:base,description:'祖仁泽发起的个人生活记录工具，手机与电脑可通过免费通用网页版记录和整理材料，Mac 另有自动采集端。',applicationCategory:'LifestyleApplication',operatingSystem:'iOS, iPadOS, Android, macOS, Windows, Linux (modern browser)',softwareVersion:'1.1.0',inLanguage:'zh-CN',author:{'@id':person['@id']},downloadUrl:base+'app/',releaseNotes:`${base}releases/universal/`,offers:{'@type':'Offer',price:'0',priceCurrency:'CNY',url:base+'app/'}};
const escape = s => String(s).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const card = (n,title,copy) => `<article class="feature"><span class="number">${n}</span><h3>${title}</h3><p>${copy}</p></article>`;
const questions = [
 ['人生档案是什么？','人生档案是祖仁泽发起的个人生活记录工具。Mac 桌面版在本机整理可授权读取的电脑活动、浏览记录、文档和媒体原件索引，帮助使用者按关键词、类型和日期找回生活线索。通用网页版免费开放，手机与电脑可以记录、导入原件、录音和备份，无需注册。'],
 ['人生档案是谁发起的？','项目由祖仁泽发起。公开介绍、源码和 1.0 安装包通过祖仁泽的 GitHub 账号 zurenze1 发布；作者页连接其个人网站。'],
 ['手机、Windows 和 Intel Mac 能用吗？','可以使用免费通用网页版 1.1。现代浏览器支持 iPhone、iPad、安卓、Mac（含 Intel）、Windows 和 Linux 的基础记录功能。可以导入文件、录音、搜索、导出完整备份；添加到桌面和媒体播放依浏览器能力而定。它不自动读取其他 App。'],
 ['换设备可以同步吗？','通用版当前没有自动云同步。档案保存在当前设备浏览器，导出完整备份后可在另一台设备导入；不同浏览器与桌面模式可能使用不同存储。请定期备份。'],
 ['Mac 自动采集端在哪里下载？','1.0 安装包可在 GitHub Releases 免费下载，适用于 macOS 13 及以上的 Apple 芯片 Mac（arm64）。Intel Mac、Windows、iPhone 和安卓独立安装包尚未发布。首版没有 Apple Developer ID 签名或公证，首次打开可能被系统拦截。'],
 ['会把个人信息自动上传到云端吗？','通用网页版将文字与附件保存在当前浏览器，不自动上传；Mac 采集端保存在本机。公开介绍不展示个人记录。清除网站数据或系统回收存储可能丢失浏览器档案，请导出完整备份。使用者可以主动导出 JSON，也可以暂停来源、调整采集目录。'],
 ['能读取微信、美团、京东和所有 App 吗？','1.0 不能完整读取所有 App。微信可检测目录与保护状态，不解密受保护的聊天库；使用者可导入自己导出的材料。美团、京东等订单可通过含明确文字日期和商品字段的 CSV / XLSX 导出文件整理，目前没有这些平台的实时订单接口。'],
 ['支持照片、视频、录音、Word、Excel 和 PDF 吗？','支持照片、视频与音频原件索引，使用者可主动录音。DOCX、XLSX、可提取文字的 PDF，以及 TXT、Markdown、CSV、ICS 可提取文字。旧 DOC / XLS 和较大文件只保留索引；扫描件 OCR、画面识别和录音转写尚未接入。'],
 ['能通过电脑读取手机数据吗？','仅支持部分已有、可访问的未加密 iPhone Finder 备份。安卓需要已安装的官方 adb 和已授权连接，当前仅适配应用清单。设备权限、加密和未连接状态会限制读取，不代表手机内所有应用内容已接入。'],
 ['自动记录能证明我吃过什么、做过什么吗？','不能。订单不证明实际吃过，日程不证明已经完成，网页访问和前台应用采样也不能证明具体操作。自动线索用于回顾，实际经历由使用者确认。'],
 ['安装后何时记录，如何停止？','应用运行期间每 15 秒采样一次前台应用，每 30 分钟整理支持的来源。关闭窗口后留在菜单栏；选择“退出并停止采集”结束运行。锁屏、空闲超过 2 分钟或睡眠时停止前台应用采样。']
];
const home = `
<section class="hero"><div class="hero-copy"><p class="eyebrow">祖仁泽发起 · 个人生活记录工具</p><h1>人生档案<span>你走过的日子，<br>值得被记住。</span></h1><p class="lead">少打一点字，留下更多生活线索。<br>手机、平板、电脑，打开浏览器就能开始。<br>让每个人都能用已有材料，慢慢整理一份人生档案。</p><div class="actions"><a class="button primary" href="${base}app/">免费开始使用 <span aria-hidden="true">→</span></a><a class="button secondary" href="${base}releases/universal/">手机与电脑怎么用</a></div><p class="small">通用网页版 · 无需注册 · 档案保存在当前设备<br>iPhone / 安卓 / iPad / Mac / Windows / Linux · 现代浏览器</p></div>
<div class="archive-art" aria-label="生活线索示意，非用户数据"><div class="art-top"><span>生活的碎片</span><span>逐渐成为故事</span></div><div class="orbit" aria-hidden="true"><i></i><b>一生</b></div><div class="fragment f1"><span>01 / 阅读</span><strong>一份值得重读的文档</strong><small>Word · Excel · PDF</small></div><div class="fragment f2"><span>02 / 日常</span><strong>一段留在电脑里的足迹</strong><small>一段文字或导出的线索</small></div><div class="fragment f3"><span>03 / 记忆</span><strong>一张照片，一段声音</strong><small>照片 · 视频 · 录音原件索引</small></div><p class="art-caption">示意内容 · 通用版数据存于当前浏览器</p></div></section>
<section class="intro section"><p class="eyebrow">从留下线索，到找回过去</p><h2>记录不必总是从打字开始。</h2><p class="section-lead">人生档案把已有材料整理为可以搜索的时间线。它提供线索，真实的生活由你确认。</p><div class="features">${card('01','每个人都能开始','手机和电脑打开浏览器即可免费使用，无需注册。Mac 用户还可选择自动采集端。')}${card('02','找回过去的自己','按关键词、类型和日期搜索，回到原始文档、照片或影音文件。')}${card('03','自己掌握档案','通用版材料存于当前浏览器，可备份和迁移。Mac 采集端可调整来源与暂停采集。')}</div></section>
<section class="section scope"><div><p class="eyebrow">通用版与 Mac 采集端</p><h2>先把能读取的，<br>好好整理起来。</h2><p>免费通用版已提供：手动记录、导入原件、文档文字提取、录音、搜索与备份。Mac 1.0 另有自动采集。手机各 App 的自动读取仍需分别适配。</p><a class="text-link" href="${base}faq/">查看功能与常见问题 →</a></div><div class="scope-list"><div><span>可以整理</span><p>支持的浏览记录 · 前台应用活动<br>DOCX / XLSX / PDF 文字<br>照片、视频、音频原件索引 · 主动录音</p></div><div><span>有条件支持</span><p>导出的订单与聊天材料<br>部分 Apple 本地数据<br>部分未加密 iPhone 备份 · 安卓应用清单</p></div><div><span>尚未接入</span><p>所有 App 完整聊天或订单 · 影音自动识别<br>录音转写 · 多设备实时同步<br>各平台原生安装包（Mac arm64 1.0 除外）</p></div></div></section>
<section class="section author-band"><div><p class="eyebrow">发起人 / 祖仁泽</p><h2>让生活留下线索，<br>也留下一点理解自己的空间。</h2><p>祖仁泽发起人生档案，希望通过已有材料与自动记录，降低整理个人经历的门槛。当前提供免费通用网页版 1.1，以及 Mac 自动采集端 1.0。</p></div><div class="author-links"><a href="${base}author/">认识发起人祖仁泽 <span>→</span></a><a href="${personal}">祖仁泽个人网站 <span>↗</span></a><a href="${repo}">项目源码与说明 <span>↗</span></a></div></section>
<section class="section closing"><p class="eyebrow">你的档案，从今天开始</p><h2>让那些日常，<br>有地方可以找回来。</h2><a class="button primary" href="${base}app/">免费开始记录 →</a><p class="small">无需购买设备或注册账号。<a href="${base}releases/1-0/">Mac 自动采集端说明</a>。</p></section>`;
const author = `<section class="page-hero"><p class="eyebrow">人生档案 · 发起人</p><h1>祖仁泽<span>把生活线索，<br>留给未来的自己。</span></h1><p class="lead">祖仁泽是人生档案项目的发起人。这个工具从“少打字，也能记录自己的经历”出发，逐步整理一份属于使用者自己的个人档案。</p><div class="actions"><a class="button primary" href="${personal}">祖仁泽个人网站 ↗</a><a class="button secondary" href="${repo}">项目 GitHub ↗</a></div></section><section class="section prose"><h2>祖仁泽与人生档案</h2><p>人生档案由祖仁泽发起，通过 GitHub 账号 zurenze1 发布公开源码与安装包。项目的目标是让使用者更容易留住生活线索，回顾自己的经历，少一些重复输入。</p><p>项目面向大众：免费通用网页版 1.1 支持手机与电脑的记录、原件导入、文档解析、录音与备份；另提供 Mac 1.0 本地采集端，整理已适配、可授权读取的电脑活动、浏览记录、文档和媒体原件索引。真实经历和线索含义仍需要使用者确认。</p><p>“祖仁泽”是发起人的姓名；“人生档案”是工具名称，英文项目名为 Life Archive。</p><h2>公开入口</h2><ul class="resource-list"><li><a href="${base}">人生档案工具介绍</a><span>功能、下载和版本状态</span></li><li><a href="${base}releases/1-0/">人生档案 1.0 发布说明</a><span>适用设备与实际能力</span></li><li><a href="${personal}">祖仁泽个人网站</a><span>发起人的公开个人介绍</span></li><li><a href="${repo}">GitHub：zurenze1/life-archive</a><span>源码、使用说明与反馈</span></li></ul><p class="updated">页面更新：${date}。本页介绍项目与发起人，不展示使用者的个人档案。</p></section>`;
const faq = `<section class="page-hero"><p class="eyebrow">人生档案 · 功能与使用</p><h1>常见问题<span>先看清楚，<br>再开始记录。</span></h1><p class="lead">关于通用网页版、Mac 采集端、支持的材料、数据保存与读取范围。</p></section><section class="section prose faq">${questions.map(([q,a])=>`<article><h2>${q}</h2><p>${a}</p></article>`).join('')}<div class="note"><p>更细的解析上限与来源状态见 <a href="${repo}/blob/main/docs/CAPABILITIES.md">1.0 功能范围</a>。使用反馈可在 <a href="${repo}/issues">GitHub Issues</a> 提交；请避免公开上传个人档案和私人聊天。</p></div><p class="updated">更新：${date} · 发起人：<a href="${base}author/">祖仁泽</a></p></section>`;
const releasePage = `<article><header class="page-hero"><p class="eyebrow">人生档案 · 公开版本</p><h1>Mac 1.0<span>从自己的电脑，<br>开始留住生活线索。</span></h1><p class="lead">祖仁泽发起的人生档案，现提供 Mac 本地测试版。免费下载安装，个人档案保存在使用者自己的电脑。</p><p class="small">发布说明：${date} · <a href="${base}author/">祖仁泽</a></p><div class="actions"><a class="button primary" href="${release}">前往 GitHub 下载 ↗</a></div></header><section class="section prose"><h2>下载安装</h2><ol><li>在 GitHub 发布页下载 <code>LifeArchive-1.0.0-arm64.dmg</code>。</li><li>打开 DMG，把“人生档案”拖入“应用程序”。</li><li>打开应用，在“采集来源”查看读取状态，在“设置与数据”调整采集目录。</li></ol><div class="note"><p>需要 macOS 13+ 与 Apple 芯片（arm64）。首版未经过 Apple Developer ID 签名或公证，可能被系统拦截；请先参考 <a href="https://support.apple.com/en-us/102445">Apple 官方说明</a> 判断是否信任。</p></div><h2>首版可以做什么</h2><ul><li>运行期间采样前台应用，整理支持的浏览记录与可访问文件。</li><li>提取 TXT、Markdown、CSV、ICS、DOCX、XLSX 和 PDF 的可读文字。</li><li>索引照片、视频、音频原件；支持主动录音。</li><li>按关键词、类型与日期搜索；可以打开来源、暂停采集与导出 JSON。</li></ul><h2>范围与测试</h2><p>普通文件文字解析上限为每文件 12 MB；PDF 最多 30 页，Excel 最多 10 个工作表且每表 2,000 行。旧 DOC / XLS、较大文件与影音目前仅索引原件。没有扫描件 OCR 或录音转写。</p><p>本机 11 项自动测试通过；发布包经过启动、SQLite、原生前台接口、PDF 提取、签名完整性和安装包完整性检查。测试结果不代表所有设备和 App 均可读取。详见 <a href="${repo}/blob/main/docs/TESTING.md">验证记录</a>。</p><p>微信加密聊天库不解密；未连接手机、受系统权限限制或未适配的内容会标明实际状态。订单、日程和浏览记录是待确认的生活线索。</p><h2>版本与反馈</h2><p>当前版本 1.0.0。Windows、Intel Mac 与手机独立安装包，以及多设备实时同步，尚未发布。</p><p><a href="${repo}/issues">提交使用反馈</a> · <a href="${repo}/blob/main/docs/CAPABILITIES.md">完整功能范围</a> · <a href="${base}faq/">常见问题</a></p></section></article>`;
const universal = `<article><header class="page-hero"><p class="eyebrow">人生档案 · 免费通用版 1.1</p><h1>每个人，都能开始。<span>手机与电脑，<br>打开浏览器就能用。</span></h1><p class="lead">祖仁泽希望人生档案普惠大众。免费通用版面向 iPhone、iPad、安卓、Mac、Windows 和 Linux 的现代浏览器，无需注册、无需指定型号。</p><div class="actions"><a class="button primary" href="${base}app/">免费开始使用 →</a></div></header><section class="section prose"><h2>通用版现在可以做什么</h2><ul><li>记录文字，按日期、类型与关键词查找时间线。</li><li>导入照片、视频、录音及文件，保留原件；可用设备还能拍照和直接录音。</li><li>提取 DOCX、XLSX、PDF、TXT、Markdown、CSV、ICS 的可读文字。旧 DOC / XLS 只保留原件。</li><li>导出包含文字与原件的完整备份，在另一台设备导入；大档案自动分批。</li><li>支持的浏览器可添加到桌面；离线缓存准备后可使用核心功能。</li><li>移除的记录可从回收站恢复，不自动永久清空。</li></ul><h2>各设备怎么开始</h2><p>直接打开通用版链接即可使用。iPhone / iPad 建议使用 Safari，并可通过分享菜单“添加到主屏幕”；安卓建议 Chrome。电脑可使用现代浏览器，支持时可安装为桌面网页应用。</p><p>基础使用需要 JavaScript 与 IndexedDB。录音、拍照、安装入口、媒体格式和浏览器存储取决于设备与浏览器能力。不支持的媒体仍可下载原件；内置浏览器受限时，可在系统浏览器打开。</p><h2>自己的档案，自己保留</h2><p>档案保存在当前设备的浏览器，不自动上传。无需账号意味着这里没有登录锁，共用该浏览器的人可能访问档案。不同设备、不同浏览器或添加到桌面模式可能独立存储，当前不提供自动云同步。</p><p>清除网站数据或系统回收存储可能丢失档案，请定期导出完整备份。备份含私人文字与原件，不要公开分享。可以请求浏览器保留存储，但浏览器可能拒绝。</p><h2>自动采集与当前范围</h2><p>通用网页不会直接读取其他 App 的聊天或订单。可导入自己导出的文件；Mac arm64 用户可另用 <a href="${base}releases/1-0/">1.0 自动采集端</a>。其他系统的原生采集、影音识别、转写和自动同步尚未上线。</p><p>单个附件最多 50 MB；文档解析最多 12 MB / 30,000 字符；PDF 最多 30 页；Excel 最多 10 个工作表、每表 2,000 行。备份每次导入最多 100 MB、10,000 条。文件日期来自修改时间，是待确认的线索；订单不证明实际食用。</p><p class="updated">发布说明：2026-10-06 · <a href="${base}author/">祖仁泽</a></p></section></article>`;
const pages = [
 {slug:'',title:'人生档案 — 祖仁泽发起的个人生活记录工具',description:'祖仁泽发起的人生档案免费通用版，iPhone、安卓、Mac、Windows 等可通过浏览器记录生活，导入照片、录音、Word、Excel、PDF；Mac 另有自动采集端。',body:home,kind:'WebPage'},
 {slug:'author/',title:'祖仁泽 — 人生档案发起人',description:'祖仁泽发起人生档案，希望人人都能留下生活线索。免费通用版支持手机与电脑，通过浏览器使用；了解项目初衷、实际范围及公开入口。',body:author,kind:'ProfilePage'},
 {slug:'faq/',title:'人生档案常见问题 — 手机、电脑与数据保存',description:'人生档案通用版与 Mac 采集端常见问题：手机和电脑使用、文件与录音、本地保存、完整备份、自动读取范围及限制。祖仁泽发起。',body:faq,kind:'WebPage'},
 {slug:'releases/universal/',title:'人生档案免费通用版 — iPhone、安卓、Mac 与 Windows',description:'人生档案 1.1 免费通用版面向大众。现代浏览器打开即用，支持生活记录、照片影音原件、Word/Excel/PDF 文字、录音、搜索和完整备份；祖仁泽发起。',body:universal,kind:'WebPage'},
 {slug:'releases/1-0/',title:'人生档案 Mac 1.0 发布说明 — 祖仁泽',description:'祖仁泽发起的人生档案 1.0 Mac 本地测试版：免费下载、安装步骤、生活线索搜索、文档解析与媒体索引、验证记录及尚未接入的能力。',body:releasePage,kind:'WebPage'}
];
for(const p of pages){
 const url=base+p.slug;
 const page={'@type':p.kind,'@id':url+'#page',url,name:p.title,description:p.description,inLanguage:'zh-CN',dateModified:date,isPartOf:{'@id':base+'#website'},author:{'@id':person['@id']},mainEntity:{'@id':p.kind==='ProfilePage'?person['@id']:app['@id']}};
 const graph=[person,{'@type':'WebSite','@id':base+'#website',url:base,name:'人生档案',inLanguage:'zh-CN',publisher:{'@id':person['@id']}},app,page];
 if(p.slug)graph.push({'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'人生档案',item:base},{'@type':'ListItem',position:2,name:p.title,item:url}]});
 if(p.slug==='releases/1-0/')graph.push({'@type':'Article','@id':url+'#article',headline:'人生档案 Mac 1.0 发布说明',datePublished:date,dateModified:date,author:{'@id':person['@id']},publisher:{'@id':person['@id']},mainEntityOfPage:{'@id':page['@id']},about:{'@id':app['@id']},inLanguage:'zh-CN'});
 const nav=[['','工具介绍'],['author/','祖仁泽'],['faq/','常见问题'],['releases/universal/','通用版']].map(([slug,label])=>`<a href="${base+slug}"${slug===p.slug?' aria-current="page"':''}>${label}</a>`).join('');
 const html=`<!doctype html>\n<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escape(p.title)}</title><meta name="description" content="${escape(p.description)}"><meta name="author" content="祖仁泽"><meta name="robots" content="index,follow,max-image-preview:large"><meta name="theme-color" content="#101611"><link rel="canonical" href="${url}"><link rel="icon" href="${base}assets/icon.png"><link rel="stylesheet" href="${base}assets/style.css?v=${styleVersion}"><meta property="og:type" content="${p.slug==='releases/1-0/'?'article':'website'}"><meta property="og:locale" content="zh_CN"><meta property="og:site_name" content="人生档案"><meta property="og:title" content="${escape(p.title)}"><meta property="og:description" content="${escape(p.description)}"><meta property="og:url" content="${url}"><meta property="og:image" content="${base}assets/share.png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="人生档案，祖仁泽发起的个人生活记录工具"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${escape(p.title)}"><meta name="twitter:description" content="${escape(p.description)}"><meta name="twitter:image" content="${base}assets/share.png"><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@graph':graph}).replaceAll('<','\\u003c')}</script></head><body><a class="skip" href="#main">跳到正文</a><header class="header wrap"><a class="brand" href="${base}"><img src="${base}assets/icon.png" width="34" height="34" alt=""><span>人生档案<small>LIFE ARCHIVE</small></span></a><nav aria-label="主导航">${nav}</nav></header><main id="main" class="wrap">${p.slug?`<nav class="breadcrumb" aria-label="面包屑"><a href="${base}">人生档案</a><span>/</span><span>${p.slug==='author/'?'祖仁泽':p.slug==='faq/'?'常见问题':p.slug==='releases/universal/'?'免费通用版':'Mac 1.0'}</span></nav>`:''}${p.body}</main><footer class="footer wrap"><div><strong>人生档案</strong><p>祖仁泽发起 · 个人生活记录工具</p></div><nav aria-label="页脚导航"><a href="${base}author/">发起人：祖仁泽</a><a href="${personal}">个人网站</a><a href="${repo}">GitHub</a><a href="${base}sitemap.xml">网站地图</a></nav><p class="footer-bottom">© 2026 祖仁泽 · 说明更新 ${date} · 个人档案保存在使用者本机</p></footer></body></html>\n`;
 const dir=path.join(root,p.slug);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'index.html'),html);
}
fs.writeFileSync(path.join(root,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${[...pages,{slug:'app/'}].map(p=>`<url><loc>${base+p.slug}</loc><lastmod>${date}</lastmod></url>`).join('')}</urlset>\n`);
fs.writeFileSync(path.join(root,'llms.txt'),`# 人生档案（Life Archive）\n\n> 祖仁泽发起的个人生活记录工具。免费通用网页版 1.1.0 面向手机与电脑现代浏览器；另有 Mac 本地采集端 1.0.0。\n\n## 公开资料\n\n- [免费通用网页版](${base}app/)：在当前浏览器记录、导入、录音与完整备份\n- [通用版说明](${base}releases/universal/)：各设备用法、存储和边界\n- [工具介绍](${base})：功能与下载\n- [祖仁泽作者页](${base}author/)：项目发起人及公开入口\n- [常见问题](${base}faq/)：真实范围与限制\n- [1.0 发布说明](${base}releases/1-0/)：安装与验证\n- [公开源码](${repo})\n\n## 实际能力\n\n通用版在当前设备浏览器保存文字、DOCX/XLSX/PDF 可读内容、照片影音原件，支持主动录音、搜索、回收站与含附件的分批 JSON 备份。数据不自动上传。Mac 采集端另有支持的电脑活动与浏览记录整理。\n\n## 限制\n\n通用网页版不读取其他 App 内部数据，不提供自动云同步。Mac 采集端也不完整读取所有 App；不解密微信聊天库。尚无影音识别、录音转写、多设备实时同步或手机独立安装包。订单、日程与访问记录只是待确认线索，不能证明实际经历。\n\n说明更新：${date}。本文是公开内容导览，不代表搜索引擎或 AI 已收录。\n`);
fs.writeFileSync(path.join(root,'facts.json'),JSON.stringify({name:'人生档案',alternateName:'Life Archive',founder:'祖仁泽',url:base,authorUrl:base+'author/',personalWebsite:personal,repository:repo,version:'1.1.0',updated:date,platform:'Modern browser on iOS, iPadOS, Android, macOS, Windows, Linux',startUrl:base+'app/',desktopVersion:'1.0.0',desktopPlatform:'macOS 13+ Apple Silicon',desktopDownloadUrl:download,dataStorage:'使用者本机，不自动上传',capabilities:['手动生活记录','DOCX/XLSX/PDF 可读文字','照片影音原件本地保存','主动录音（浏览器支持时）','搜索与回收站','含附件的完整 JSON 备份与手动迁移'],desktopCapabilities:['支持的浏览记录','前台应用采样','本机文件与媒体原件索引'],notAvailable:['所有 App 全量读取','微信加密库解密','影音识别','录音转写','多设备实时同步','手机独立安装包'],documentation:base+'faq/'},null,2)+'\n');
fs.writeFileSync(path.join(root,'.nojekyll'),'');
const web = path.join(__dirname, '..', 'web');
const webFiles = fs.readdirSync(web, {recursive:true}).filter(f => fs.statSync(path.join(web,f)).isFile()).sort();
const buildHash = require('node:crypto').createHash('sha256');
for (const f of webFiles) {buildHash.update(f);buildHash.update(fs.readFileSync(path.join(web,f)));}
const webVersion=buildHash.digest('hex').slice(0,12);
fs.cpSync(web,path.join(root,'app'),{recursive:true});
for(const f of ['index.html','sw.js',...webFiles.filter(f=>f.endsWith('.mjs')&&!f.startsWith('vendor/'))]) {
 const target=path.join(root,'app',f);let contents=fs.readFileSync(target,'utf8').replaceAll('__BUILD_VERSION__',webVersion);
 if(f.endsWith('.mjs'))contents=contents.replace(/(['"])(\.\/(?:model|db|documents|doc-worker|vendor\/(?:fflate|pdf|pdf\.worker))\.mjs)\1/g,(_,quote,url)=>quote+url+'?v='+webVersion+quote);
 fs.writeFileSync(target,contents);
}
console.log(`Built ${pages.length+1} public HTML pages, universal app, sitemap and content guides.`);
