const api=window.archive,$=id=>document.getElementById(id);
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={diary:'日记',activity:'应用使用',browser:'浏览记录',file:'文档',media:'照片 / 影音',message:'信息',order:'订单',calendar:'日程'};
const statuses={ready:'可读取',partial:'部分可读取',missing:'未发现 / 未连接',blocked:'访问受限',unsupported:'尚未适配',error:'读取失败',scanning:'检查中',paused:'已暂停'};
let state,offset=0,view='timeline',searchTimer,recorder,stream,chunks=[],recordTimer;
function toast(message){$('toast').textContent=message;$('toast').classList.remove('hidden');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),6500);}
async function action(fn,success){try{const result=await fn();if(result?.error){toast(result.error);return result;}if(success&&!result?.cancelled)toast(typeof success==='function'?success(result):success);await refresh();return result;}catch(error){toast(error.message);}}
async function refresh(){state=await api.state();if(state.error)return toast(state.error);const s=state.summary;$('total').textContent=s.total.toLocaleString();$('today').textContent=s.today.toLocaleString();$('app-count').textContent=s.appCount;$('source-count').textContent=s.sources.filter(item=>['ready','partial'].includes(item.status)&&!['apps','activity'].includes(item.id)).length;$('running').textContent=state.tracking?'本机自动整理中':'已暂停采集';$('tracking').textContent=state.tracking?'暂停采集':'继续采集';$('scan').disabled=state.scanning;$('scan').textContent=state.scanning?'正在整理…':'立即整理';if(!state.scanning)$('progress').textContent=s.lastScan?'上次整理 '+new Date(s.lastScan).toLocaleString('zh-CN'):'等待第一次整理';$('login').checked=state.login;if(state.reminderPending&&!$('reminder-prompt').open&&!$('diary-editor').open){$('reminder-preview').textContent=state.reminderTest?'这是测试提醒，不会改变今天的记录状态。':'';state.reminder.strong?$('reminder-prompt').showModal():$('reminder-prompt').show();}if(!state.reminderPending&&$('reminder-prompt').open)$('reminder-prompt').close();if(view==='sources')renderSources();if(view==='settings')renderSettings();if(['people','themes','observer','decisions'].includes(view))await studio.update();if(view==='timeline')await load(false);}
async function load(append=false){if(!append)offset=0;const result=await api.records({query:$('search').value,kind:$('kind').value,day:$('day').value,offset});if(result.error)return toast(result.error);$('result-count').textContent=`${result.total.toLocaleString()} 条匹配线索`;$('more').classList.toggle('hidden',offset+result.records.length>=result.total);const html=result.records.map(row=>{const date=new Date(row.occurredAt),day=date.toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric'}),time=date.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false});return `<article class="record"><div class="record-time">${escape(time)}<br>${escape(date.toLocaleDateString('zh-CN',{month:'numeric',day:'numeric'}))}</div><div><h3><span class="badge">${escape(labels[row.kind]??row.kind)}</span>${escape(row.title)}</h3><p>${escape(row.body.slice(0,350))}</p><small class="studio-muted">${escape([row.meta.pinned?'置顶':'',...(row.meta.people??[]),...(row.meta.tags??[])].filter(Boolean).join(' · '))}</small>${row.body.length>350?`<details><summary>展开文字</summary><p>${escape(row.body)}</p></details>`:''}<div class="record-bottom"><span>${escape(day)}</span><span>${escape(state.summary.sources.find(item=>item.id===row.source)?.name??row.source)}</span><button class="text-button" data-detail="${escape(row.id)}">补充 / 确认经历 →</button>${row.path||row.url?`<button class="text-button" data-open="${escape(row.id)}">打开原始来源 ↗</button>`:''}</div></div></article>`;}).join('');if(append)$('records').insertAdjacentHTML('beforeend',html);else $('records').innerHTML=html||'<div class="empty">这里还没有匹配的记录。<br>可以整理电脑、导入文件，或直接录音。</div>';offset+=result.records.length;}
function renderSources(){$('sources').innerHTML=state.summary.sources.map(item=>`<article class="source-card"><div class="source-top"><h3>${escape(item.name)}</h3><span class="source-status ${escape(item.status)}">${escape(statuses[item.status]??item.status)}</span></div><p>${escape(item.detail)}</p><div class="source-bottom"><span>${item.count.toLocaleString()} 条记录</span><label><input type="checkbox" data-source="${escape(item.id)}" ${state.disabled.includes(item.id)?'':'checked'}> 启用</label></div></article>`).join('');$('apps').innerHTML=state.apps.map(item=>`<div title="${escape(item.access)}">${escape(item.name)}<small>可记录前台使用 · 内容按来源接入</small></div>`).join('');}
function renderSettings(){renderReminderSettings();$('folders').innerHTML=state.folders.map(folder=>`<div class="folder"><span>${escape(folder)}</span><button class="text-button" data-remove="${escape(folder)}">移除</button></div>`).join('');if(document.activeElement!==$('web-url'))$('web-url').value=state.webUrl??'';}
document.querySelectorAll('nav button').forEach(button=>button.addEventListener('click',async()=>{view=button.dataset.view;document.querySelectorAll('nav button').forEach(item=>item.classList.toggle('active',item===button));['timeline','sources','settings'].forEach(name=>$(name+'-view').classList.toggle('hidden',name!==view));$('life-studio').hidden=!['people','themes','observer','decisions'].includes(view);document.querySelector('.desktop-prologue').hidden=view!=='timeline';$('metrics').hidden=view!=='timeline';const cinema=document.querySelector('.desktop-prologue video');if(view==='timeline'&&!matchMedia('(prefers-reduced-motion: reduce)').matches)cinema.play().catch(()=>{});else cinema.pause();if(['people','themes','observer','decisions'].includes(view))await studio.activate(view);$('page-title').textContent={people:'人物档案',themes:'生活主题',observer:'旁观自己',decisions:'人生选择',timeline:'我的时间线',sources:'采集来源',settings:'设置与数据'}[view];$('subtitle').textContent={people:'沿着人物，找回你们一起走过的日子。',themes:'读懂反复出现的生活主题。',observer:'每次观察，都能回到原始经历。',decisions:'保留理由、期待与结果，让过去为未来提供参照。',timeline:'让日常自己留下线索，回头查找更容易。',sources:'查看每个来源实际能读到什么。',settings:'你决定何时记录、存在哪里、如何保留。'}[view];await refresh();}));
$('search').addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>load(false),250);});['kind','day'].forEach(id=>$(id).addEventListener('change',()=>load(false)));$('more').onclick=()=>load(true);
$('scan').onclick=()=>action(()=>api.scan());$('tracking').onclick=()=>action(()=>api.tracking(!state.tracking),()=>state.tracking?'采集已暂停':'继续采集');$('import').onclick=()=>action(()=>api.import(),result=>`已导入 ${result.count} 个文件`);$('folder-add').onclick=()=>action(()=>api.folderAdd());$('export').onclick=()=>action(()=>api.export(),'档案已导出');$('reveal').onclick=()=>api.revealData();$('privacy').onclick=()=>api.privacy();$('website').onclick=()=>action(()=>api.website());$('web-url-save').onclick=()=>action(()=>api.webUrl($('web-url').value),'网页版地址已保存');$('android-help').onclick=()=>api.androidHelp();$('login').onchange=()=>action(()=>api.login($('login').checked),'登录启动设置已更新');$('clear').onclick=()=>action(()=>api.clear(),'档案已清空并暂停');
document.addEventListener('click',event=>{const open=event.target.closest('[data-open]'),remove=event.target.closest('[data-remove]');const detail=event.target.closest('[data-detail]');if(detail)openRecordDetail(detail.dataset.detail);if(open)action(()=>api.openRecord(open.dataset.open));if(remove)action(()=>api.folderRemove(remove.dataset.remove),'已移除此文件夹');});document.addEventListener('change',event=>{if(event.target.dataset.source)action(()=>api.sourceToggle(event.target.dataset.source,event.target.checked));});
function releaseMic(){clearInterval(recordTimer);if(stream)stream.getTracks().forEach(track=>track.stop());stream=null;$('record').classList.remove('recording');$('record').textContent='● 录音';}
$('record').onclick=async()=>{if(recorder?.state==='recording'){recorder.stop();return;}const permission=await api.recordStart();if(permission.error)return toast(permission.error);try{stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];recorder=new MediaRecorder(stream,{mimeType:'audio/webm'});recorder.ondataavailable=event=>{if(event.data.size)chunks.push(event.data);};recorder.onstop=async()=>{releaseMic();const bytes=new Uint8Array(await new Blob(chunks,{type:'audio/webm'}).arrayBuffer());await action(()=>api.recordSave(bytes),'原始录音已保存');};recorder.onerror=()=>{releaseMic();toast('录音中断，请重试。');};recorder.start(1000);let seconds=0;$('record').classList.add('recording');$('record').textContent='■ 停止并保存 0:00';recordTimer=setInterval(()=>{seconds++;$('record').textContent=`■ 停止并保存 ${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;if(seconds>=1800)recorder.stop();},1000);}catch(error){releaseMic();toast('录音未能开始：'+error.message);}};
api.onProgress(progress=>{if(progress.source)$('progress').textContent='正在检查：'+progress.source;if(progress.done){toast(`整理完成，新增 ${progress.stats.added.toLocaleString()} 条线索`);refresh();}});
document.getElementById('diary-metadata').innerHTML=LifeArchiveStudio.fields('diary');
const studio=LifeArchiveStudio.start({load:async()=>{const r=await api.lifeState();if(r.error)throw Error(r.error);return r;},saveDecision:async d=>{const r=await api.decisionSave(d);if(r.error)throw Error(r.error);},edit:id=>openRecordDetail(id),toast});
refresh();setInterval(refresh,8000);

function renderReminderSettings(){if(!document.activeElement?.closest('#reminder-form')){ $('reminder-enabled').checked=state.reminder.enabled;$('reminder-time').value=state.reminder.time;$('reminder-strong').checked=state.reminder.strong; }$('reminder-status').textContent=(state.reminder.enabled?'每天 '+state.reminder.time+' · '+(state.reminder.strong?'强提醒':'普通提醒'):'提醒已关闭')+(state.notificationProblem?' · '+state.notificationProblem:'');}
async function openDiary(){await api.diaryEditing(true);if(!$('diary-editor').open){$('diary-day').value=new Intl.DateTimeFormat('sv-SE').format(new Date());$('diary-title').value='';$('diary-body').value='';LifeArchiveStudio.fillFields('diary',{});$('diary-editor').showModal();$('diary-body').focus();}}
$('write-diary').onclick=openDiary;$('diary-close').onclick=()=>$('diary-editor').close();$('diary-editor').addEventListener('close',()=>api.diaryEditing(false));
$('diary-form').onsubmit=async event=>{event.preventDefault();const result=await action(()=>api.diarySave({title:$('diary-title').value,body:$('diary-body').value,day:$('diary-day').value,meta:LifeArchiveStudio.readFields('diary')}),'日记已保存，今天不会再催你');if(result?.ok)$('diary-editor').close();};
$('reminder-form').onsubmit=event=>{event.preventDefault();action(()=>api.reminderSettings({enabled:$('reminder-enabled').checked,time:$('reminder-time').value,strong:$('reminder-strong').checked}),'提醒设置已保存');};
$('reminder-test').onclick=()=>action(()=>api.reminderTest());
async function reminderResponse(value){const result=await api.reminderResponse(value);if(result?.error)return toast(result.error);$('reminder-prompt').close();if(value==='write')await openDiary();await refresh();}
for(const [id,value] of [['reminder-write','write'],['reminder-snooze','snooze'],['reminder-done','done'],['reminder-disable','disable']])$(id).onclick=()=>reminderResponse(value);
$('reminder-prompt').addEventListener('cancel',event=>{event.preventDefault();reminderResponse('snooze');});
api.onReminder(()=>refresh());

let detailId;const detailDialog=document.createElement('dialog');detailDialog.className='studio-dialog';detailDialog.setAttribute('aria-label','补充与确认经历');detailDialog.innerHTML='<form id="detail-form"><div class="studio-dialog-head"><h2>补充与确认经历</h2><button type="button" class="studio-quiet" id="detail-close" aria-label="关闭经历窗口">×</button></div><h3 id="detail-title"></h3><p id="detail-body"></p><p id="detail-date" class="studio-muted"></p>'+LifeArchiveStudio.fields('detail')+'<label class="studio-check"><input type="checkbox" id="detail-confirmed"> 我确认这是自己的实际经历</label><p class="studio-muted">来源材料不能证明实际完成了某个行为，请对照自己的经历确认。</p><div class="studio-dialog-actions"><button class="studio-primary" type="submit">保存补充</button></div></form>';document.body.append(detailDialog);$('detail-close').onclick=()=>detailDialog.close();async function openRecordDetail(id){const r=await api.recordDetail(id);if(r.error)return toast(r.error);detailId=id;$('detail-title').textContent=r.title;$('detail-body').textContent=r.body;$('detail-date').textContent=new Date(r.occurred_at).toLocaleString();LifeArchiveStudio.fillFields('detail',r.meta);$('detail-confirmed').checked=r.meta.confirmed===true||(r.kind==='diary'&&r.meta.confirmed!==false);detailDialog.showModal();}$('detail-form').onsubmit=async e=>{e.preventDefault();const r=await api.recordMetadata({id:detailId,meta:LifeArchiveStudio.readFields('detail'),confirmed:$('detail-confirmed').checked});if(r.error)return toast(r.error);detailDialog.close();await refresh();await studio.update();toast('经历已补充；观察以已确认记录为依据。');};
