const api=window.archive,$=id=>document.getElementById(id);
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={activity:'应用使用',browser:'浏览记录',file:'文档',media:'照片 / 影音',message:'信息',order:'订单',calendar:'日程'};
const statuses={ready:'可读取',partial:'部分可读取',missing:'未发现 / 未连接',blocked:'访问受限',unsupported:'尚未适配',error:'读取失败',scanning:'检查中',paused:'已暂停'};
let state,offset=0,view='timeline',searchTimer,recorder,stream,chunks=[],recordTimer;
function toast(message){$('toast').textContent=message;$('toast').classList.remove('hidden');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),6500);}
async function action(fn,success){try{const result=await fn();if(result?.error){toast(result.error);return result;}if(success&&!result?.cancelled)toast(typeof success==='function'?success(result):success);await refresh();return result;}catch(error){toast(error.message);}}
async function refresh(){state=await api.state();if(state.error)return toast(state.error);const s=state.summary;$('total').textContent=s.total.toLocaleString();$('today').textContent=s.today.toLocaleString();$('app-count').textContent=s.appCount;$('source-count').textContent=s.sources.filter(item=>['ready','partial'].includes(item.status)&&!['apps','activity'].includes(item.id)).length;$('running').textContent=state.tracking?'本机自动整理中':'已暂停采集';$('tracking').textContent=state.tracking?'暂停采集':'继续采集';$('scan').disabled=state.scanning;$('scan').textContent=state.scanning?'正在整理…':'立即整理';if(!state.scanning)$('progress').textContent=s.lastScan?'上次整理 '+new Date(s.lastScan).toLocaleString('zh-CN'):'等待第一次整理';$('login').checked=state.login;if(view==='sources')renderSources();if(view==='settings')renderSettings();if(view==='timeline')await load(false);}
async function load(append=false){if(!append)offset=0;const result=await api.records({query:$('search').value,kind:$('kind').value,day:$('day').value,offset});if(result.error)return toast(result.error);$('result-count').textContent=`${result.total.toLocaleString()} 条匹配线索`;$('more').classList.toggle('hidden',offset+result.records.length>=result.total);const html=result.records.map(row=>{const date=new Date(row.occurredAt),day=date.toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric'}),time=date.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false});return `<article class="record"><div class="record-time">${escape(time)}<br>${escape(date.toLocaleDateString('zh-CN',{month:'numeric',day:'numeric'}))}</div><div><h3><span class="badge">${escape(labels[row.kind]??row.kind)}</span>${escape(row.title)}</h3><p>${escape(row.body.slice(0,350))}</p>${row.body.length>350?`<details><summary>展开文字</summary><p>${escape(row.body)}</p></details>`:''}<div class="record-bottom"><span>${escape(day)}</span><span>${escape(state.summary.sources.find(item=>item.id===row.source)?.name??row.source)}</span>${row.path||row.url?`<button class="text-button" data-open="${escape(row.id)}">打开原始来源 ↗</button>`:''}</div></div></article>`;}).join('');if(append)$('records').insertAdjacentHTML('beforeend',html);else $('records').innerHTML=html||'<div class="empty">这里还没有匹配的记录。<br>可以整理电脑、导入文件，或直接录音。</div>';offset+=result.records.length;}
function renderSources(){$('sources').innerHTML=state.summary.sources.map(item=>`<article class="source-card"><div class="source-top"><h3>${escape(item.name)}</h3><span class="source-status ${escape(item.status)}">${escape(statuses[item.status]??item.status)}</span></div><p>${escape(item.detail)}</p><div class="source-bottom"><span>${item.count.toLocaleString()} 条记录</span><label><input type="checkbox" data-source="${escape(item.id)}" ${state.disabled.includes(item.id)?'':'checked'}> 启用</label></div></article>`).join('');$('apps').innerHTML=state.apps.map(item=>`<div title="${escape(item.access)}">${escape(item.name)}<small>可记录前台使用 · 内容按来源接入</small></div>`).join('');}
function renderSettings(){$('folders').innerHTML=state.folders.map(folder=>`<div class="folder"><span>${escape(folder)}</span><button class="text-button" data-remove="${escape(folder)}">移除</button></div>`).join('');if(document.activeElement!==$('web-url'))$('web-url').value=state.webUrl??'';}
document.querySelectorAll('nav button').forEach(button=>button.addEventListener('click',async()=>{view=button.dataset.view;document.querySelectorAll('nav button').forEach(item=>item.classList.toggle('active',item===button));['timeline','sources','settings'].forEach(name=>$(name+'-view').classList.toggle('hidden',name!==view));$('page-title').textContent={timeline:'我的时间线',sources:'采集来源',settings:'设置与数据'}[view];$('subtitle').textContent={timeline:'让日常自己留下线索，回头查找更容易。',sources:'查看每个来源实际能读到什么。',settings:'你决定何时记录、存在哪里、如何保留。'}[view];await refresh();}));
$('search').addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>load(false),250);});['kind','day'].forEach(id=>$(id).addEventListener('change',()=>load(false)));$('more').onclick=()=>load(true);
$('scan').onclick=()=>action(()=>api.scan());$('tracking').onclick=()=>action(()=>api.tracking(!state.tracking),()=>state.tracking?'采集已暂停':'继续采集');$('import').onclick=()=>action(()=>api.import(),result=>`已导入 ${result.count} 个文件`);$('folder-add').onclick=()=>action(()=>api.folderAdd());$('export').onclick=()=>action(()=>api.export(),'档案已导出');$('reveal').onclick=()=>api.revealData();$('privacy').onclick=()=>api.privacy();$('website').onclick=()=>action(()=>api.website());$('web-url-save').onclick=()=>action(()=>api.webUrl($('web-url').value),'网页版地址已保存');$('android-help').onclick=()=>api.androidHelp();$('login').onchange=()=>action(()=>api.login($('login').checked),'登录启动设置已更新');$('clear').onclick=()=>action(()=>api.clear(),'档案已清空并暂停');
document.addEventListener('click',event=>{const open=event.target.closest('[data-open]'),remove=event.target.closest('[data-remove]');if(open)action(()=>api.openRecord(open.dataset.open));if(remove)action(()=>api.folderRemove(remove.dataset.remove),'已移除此文件夹');});document.addEventListener('change',event=>{if(event.target.dataset.source)action(()=>api.sourceToggle(event.target.dataset.source,event.target.checked));});
function releaseMic(){clearInterval(recordTimer);if(stream)stream.getTracks().forEach(track=>track.stop());stream=null;$('record').classList.remove('recording');$('record').textContent='● 录音';}
$('record').onclick=async()=>{if(recorder?.state==='recording'){recorder.stop();return;}const permission=await api.recordStart();if(permission.error)return toast(permission.error);try{stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];recorder=new MediaRecorder(stream,{mimeType:'audio/webm'});recorder.ondataavailable=event=>{if(event.data.size)chunks.push(event.data);};recorder.onstop=async()=>{releaseMic();const bytes=new Uint8Array(await new Blob(chunks,{type:'audio/webm'}).arrayBuffer());await action(()=>api.recordSave(bytes),'原始录音已保存');};recorder.onerror=()=>{releaseMic();toast('录音中断，请重试。');};recorder.start(1000);let seconds=0;$('record').classList.add('recording');$('record').textContent='■ 停止并保存 0:00';recordTimer=setInterval(()=>{seconds++;$('record').textContent=`■ 停止并保存 ${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;if(seconds>=1800)recorder.stop();},1000);}catch(error){releaseMic();toast('录音未能开始：'+error.message);}};
api.onProgress(progress=>{if(progress.source)$('progress').textContent='正在检查：'+progress.source;if(progress.done){toast(`整理完成，新增 ${progress.stats.added.toLocaleString()} 条线索`);refresh();}});
refresh();setInterval(refresh,8000);
