/* Evidence-based archive tools. No model calls, telemetry, or inferred personality labels. */
(function(root,factory){const value=factory();root.LifeArchiveLife=value;if(typeof module==='object'&&module.exports)module.exports=value;})(typeof globalThis==='object'?globalThis:this,function(){
'use strict';
const categories=['生活','工作','学习','关系','旅行','健康','兴趣'];
const moods=['有点低落','不太轻松','平平淡淡','感觉不错','很开心'];
const text=(v,n=20000)=>String(v??'').trim().slice(0,n);
const list=v=>[...new Set((Array.isArray(v)?v:String(v??'').split(/[,，\n、]/)).map(x=>text(x,60)).filter(Boolean))].slice(0,20);
function day(value){const d=new Date(value);if(!Number.isFinite(d.getTime()))throw Error('日期无法读取');return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function validDay(s){if(!/^\d{4}-\d{2}-\d{2}$/.test(s))return false;const d=new Date(s+'T12:00:00');return Number.isFinite(d.getTime())&&day(d)===s;}
function metadata(v={}){return {people:list(v.people),tags:list(v.tags),category:categories.includes(v.category)?v.category:'生活',mood:Number.isInteger(v.mood)&&v.mood>=1&&v.mood<=5?v.mood:null,place:text(v.place,200),pinned:v.pinned===true};}
function normalizeDecision(v,now=new Date().toISOString()){
 if(!v||typeof v!=='object'||Array.isArray(v))throw Error('选择记录格式不正确');const d={id:text(v.id,200),title:text(v.title,150),day:text(v.day,10),category:categories.includes(v.category)?v.category:'工作',question:text(v.question,12000),options:[...new Set((Array.isArray(v.options)?v.options:String(v.options??'').split('\n')).map(x=>text(x,1000)).filter(Boolean))].slice(0,12),chosen:text(v.chosen,1000),reasons:text(v.reasons,12000),expected:text(v.expected,12000),concerns:text(v.concerns,12000),outcome:text(v.outcome,20000),reviewDay:text(v.reviewDay,10),status:['thinking','chosen','reviewed'].includes(v.status)?v.status:'thinking',evidenceIds:[...new Set(Array.isArray(v.evidenceIds)?v.evidenceIds.map(x=>text(x,200)):[])].slice(0,200),createdAt:typeof v.createdAt==='string'?v.createdAt:now,updatedAt:now,deletedAt:typeof v.deletedAt==='string'?v.deletedAt:null};
 if(!d.title)throw Error('请写下要考虑的选择');if(!validDay(d.day)||d.reviewDay&&!validDay(d.reviewDay))throw Error('选择记录的日期不正确');if(d.status!=='thinking'&&!d.chosen)throw Error('请写下实际做出的选择');if(d.status==='reviewed'&&!d.outcome)throw Error('复盘时请补充实际结果');return d;
}
function evidence(entries){return entries.filter(e=>!e.deletedAt&&e.confirmed===true);}
function groups(entries,key){const map=new Map();for(const e of evidence(entries)){const m=metadata(e.legacy??e.meta??e);const names=key==='category'?[m.category]:m[key]??[];for(const name of names){const g=map.get(name)??{name,ids:[],days:new Set(),lastDay:''};g.ids.push(e.id);g.days.add(e.day);if(e.day>g.lastDay)g.lastDay=e.day;map.set(name,g);}}return [...map.values()].map(g=>({...g,count:g.ids.length,days:g.days.size})).sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name));}
function related(entries,d,limit=8){const words=[...list(d.category),...text(d.title+' '+d.question+' '+d.options.join(' ')).split(/[\s，。！？、：；]+/)].filter(w=>w.length>=2);return evidence(entries).map(e=>{const m=metadata(e.legacy??e);const hay=[e.title,e.body,...m.tags,...m.people].join(' ').toLowerCase();return {e,score:words.reduce((n,w)=>n+(hay.includes(w.toLowerCase())?2:0),m.category===d.category?1:0)};}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||b.e.day.localeCompare(a.e.day)).slice(0,limit).map(x=>x.e);}
function overview(entries,now=new Date()){
 const confirmed=evidence(entries),today=day(now),start=new Date(now.getFullYear(),now.getMonth(),now.getDate()-6),since=day(start),week=confirmed.filter(e=>e.day>=since&&e.day<=today),counts=new Map();for(const e of confirmed)counts.set(e.day,(counts.get(e.day)??0)+1);
 const cells=[];for(let i=83;i>=0;i--){const d=day(new Date(now.getFullYear(),now.getMonth(),now.getDate()-i));cells.push({day:d,count:counts.get(d)??0});}
 const moodEntries=week.filter(e=>metadata(e.legacy??e).mood!==null);const averageMood=moodEntries.length?moodEntries.reduce((n,e)=>n+metadata(e.legacy??e).mood,0)/moodEntries.length:null;
 const period=confirmed.filter(e=>e.day<=today),past=new Set(period.map(e=>e.day));let streak=0;for(let i=0;i<366;i++){const d=day(new Date(now.getFullYear(),now.getMonth(),now.getDate()-i));if(!past.has(d))break;streak++;}
 return {confirmed:confirmed.length,pending:entries.filter(e=>!e.deletedAt&&!e.confirmed).length,days:counts.size,week:week.length,weekIds:week.map(e=>e.id),moodIds:moodEntries.map(e=>e.id),averageMood,streak,cells,people:groups(entries,'people'),tags:groups(entries,'tags'),categories:groups(entries,'category')};
}
function activityWatch(value){
 if(!value||typeof value.buckets!=='object'||Array.isArray(value.buckets)||!value.buckets)throw Error('请选择 ActivityWatch 导出的 buckets JSON');const output=[],seen=new Set();let skipped=0;
 for(const [bucketId,b] of Object.entries(value.buckets)){if(b.type!=='currentwindow')continue;if(!Array.isArray(b.events))throw Error('ActivityWatch 事件列表不完整');if(b.events.length>20000)throw Error('每个来源最多 20,000 条活动，请分批导出');
 const afk=Object.values(value.buckets).filter(a=>a.type==='afkstatus'&&a.hostname===b.hostname).flatMap(a=>Array.isArray(a.events)?a.events:[]).filter(e=>e.data?.status==='afk').map(e=>({start:Date.parse(e.timestamp),end:Date.parse(e.timestamp)+Number(e.duration)*1000})).filter(e=>Number.isFinite(e.start)&&Number.isFinite(e.end)).sort((a,b)=>a.start-b.start);const merged=[];for(const a of afk){const p=merged.at(-1);if(p&&a.start<=p.end)p.end=Math.max(p.end,a.end);else merged.push({...a});}
 for(const e of b.events){const start=Date.parse(e.timestamp),duration=Number(e.duration);if(!Number.isFinite(start)||!Number.isFinite(duration)||duration<=0||duration>86400){skipped++;continue;}const end=start+duration*1000,active=Math.max(0,duration-merged.reduce((n,a)=>n+Math.max(0,Math.min(end,a.end)-Math.max(start,a.start))/1000,0));if(active<1){skipped++;continue;}const key=`aw:${bucketId}:${e.id??e.timestamp}:${duration}`;if(seen.has(key)){skipped++;continue;}seen.add(key);const date=new Date(start);if(output.length>=10000)throw Error('一次最多导入 10,000 条活动，请分批导出');output.push({id:'',sourceKey:key,day:day(date),time:`${String(date.getHours()).padStart(2,'0')}:${String(date.getMinutes()).padStart(2,'0')}`,title:text(e.data?.app||'电脑活动',200),body:`${text(e.data?.title,1000)}\n非离开时段约 ${Math.round(active)} 秒。前台应用线索不证明具体行为。`,kind:'imported',source:'ActivityWatch 导入',confirmed:false,legacy:{category:'工作',tags:['设备活动'],people:[],mood:null,place:''}});}
 }if(!output.length)throw Error('没有可导入的前台活动；请选择包含 currentwindow 事件的导出文件');return {entries:output,decisions:[],attachments:[],skipped};
}
return {categories,moods,list,day,validDay,metadata,normalizeDecision,evidence,groups,related,overview,activityWatch};
});
